### Listar GET
GET http://127.0.0.1:3000/producto

### Guardar POST
POST http://127.0.0.1:3000/producto
Content-Type: application/json

{
    "nombre": "ESCRITORIO",
    "estado": true,
    "precio": 500
}

### Mostrar GET
GET http://127.0.0.1:3000/producto/2

### Modificar PATCH
PATCH http://127.0.0.1:3000/producto/2
Content-Type: application/json

{
    "nombre": "MONITOR modificado 2"
}

### Elimninar DELETE
DELETE http://127.0.0.1:3000/producto/2

